const skillData = [
  {
    id: "1",
    skillName: "HTML/CSS",
    skillVariant: "success",
    skillLabel: "100%",
    skillNow: 100,
    animated: "",
  },
  {
    id: "2",
    skillName: "ASP.NET MVC 5",
    skillVariant: "primary",
    skillLabel: "80%",
    skillNow: 80,
    animated: "animated",
  },
  {
    id: "3",
    skillName: "jQuery/JS",
    skillVariant: "warning",
    skillLabel: "75%",
    skillNow: 75,
    animated: "animated",
  },
  {
    id: "4",
    skillName: "MSSQL Server",
    skillVariant: "danger",
    skillLabel: "65%",
    skillNow: 65,
    animated: "",
  },
  {
    id: "5",
    skillName: "Web API",
    skillVariant: "info",
    skillLabel: "15%",
    skillNow: 15,
    animated: "animated",
  },
  {
    id: "6",
    skillName: "React.js",
    skillVariant: "warning",
    skillLabel: "35%",
    skillNow: 35,
    animated: "",
  },
  {
    id: "7",
    skillName: "Web Crawling",
    skillVariant: "success",
    skillLabel: "15%",
    skillNow: 15,
    animated: "animated",
  },
];
export default skillData;
